/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formacion_empresa;

import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

import formacion_empresa.view.*;

/**
 *
 * @author marcanram
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alquilaria");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main ventana = new Main();
                MenuPrincipal menuP = new MenuPrincipal();
                MenuPropietarios menu1 = new MenuPropietarios();
                MenuInquilinos menu2 = new MenuInquilinos();
                MenuViviendas menu3 = new MenuViviendas();
                MenuContratos menu4 = new MenuContratos();
                Estadisticas est = new Estadisticas();
                
                menuP.addComponentListener(new ComponentAdapter() {
                    @Override
                    public void componentShown(ComponentEvent e) {
                        ventana.setContentPane(menuP);
                    }

                    @Override
                    public void componentHidden(ComponentEvent e) {
                        if (menuP.isPropietariosVisible()) {
                            menu1.setVisible(true);
                            ventana.setContentPane(menu1);
                        }
                        else if (menuP.isInquilinosVisible()) {
                            menu2.setVisible(true);
                            ventana.setContentPane(menu2);
                        }
                        else if (menuP.isViviendasVisible()) {
                            menu3.setVisible(true);
                            ventana.setContentPane(menu3);
                        }
                        else if (menuP.isContratosVisible()) {
                            menu4.setVisible(true);
                            ventana.setContentPane(menu4);
                        }
                        else if (menuP.isEstadisticasVisible()) {
                            est.setVisible(true);
                            ventana.setContentPane(est);
                        }
                    }
                    
                });
                
                menu1.addComponentListener(new ComponentAdapter() {
                    @Override
                    public void componentHidden(ComponentEvent e) {
                        menuP.setVisible(true);
                        menuP.setPropietariosVisible(false);
                    }
                });
                
                menu2.addComponentListener(new ComponentAdapter() {
                    @Override
                    public void componentHidden(ComponentEvent e) {
                        menuP.setVisible(true);
                        menuP.setInquilinosVisible(false);
                    }
                });
                
                menu3.addComponentListener(new ComponentAdapter() {
                    @Override
                    public void componentHidden(ComponentEvent e) {
                        menuP.setVisible(true);
                        menuP.setViviendasVisible(false);
                    }
                });
                
                menu4.addComponentListener(new ComponentAdapter() {
                    @Override
                    public void componentHidden(ComponentEvent e) {
                        menuP.setVisible(true);
                        menuP.setContratosVisible(false);
                    }
                });
                
                est.addComponentListener(new ComponentAdapter() {
                    @Override
                    public void componentHidden(ComponentEvent e) {
                        menuP.setVisible(true);
                        menuP.setEstadisticasVisible(false);
                    }
                });
                
                ventana.setContentPane(menuP);
                ventana.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
